name: nico docker l

# 触发条件：当代码推送到 main 分支时触发
on:
  push:
    branches:
      - main

# 定义任务
jobs:
  build-and-test:
    # 运行环境：最新版本的 Ubuntu
    runs-on: ubuntu-latest

    # 步骤
    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 打印当前工作目录
      - name: Build project
        run: pwd
      - name: print date 
        run: date
  nico-build:
    runs-on: ubuntu-latest

    steps:
      - name: build nginx images
        run: docker pull nginx
      - name: read images 
        run: docker images
      - name: docker ps -a 
        run: docker ps

name: nico 10000

# 触发条件：当代码推送到 main 分支时触发
on:
  push:
    branches:
      - main

# 定义任务
jobs:
  build-and-test:
    # 运行环境：最新版本的 Ubuntu
    runs-on: ubuntu-latest

    # 步骤
    steps:
      - name: test0001
        run: ls -l 