name: CI Pipeline

# 触发条件：当代码推送到 main 分支时触发
on:
  push:
    branches:
      - main

# 定义任务
jobs:
  build-and-test:
    # 运行环境：最新版本的 Ubuntu
    runs-on: ubuntu-latest
      - name: Build project
        run: pwd