name: CI Pipeline

# 触发条件：当代码推送到 main 分支时触发
on:
  push:
    branches:
      - main

# 定义任务
jobs:
  build-and-test:
    # 运行环境：最新版本的 Ubuntu
    runs-on: ubuntu-latest

    # 步骤
    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 打印当前工作目录
      - name: Build project
        run: pwd
      - name: print date 
        run: date